// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMPw_E3y7BVg2zrlc1O52SFGOTXFK5KyI',
    appId: '1:791650293748:web:ee7e0e626c7f7636224ba1',
    messagingSenderId: '791650293748',
    projectId: 'nhatkychitieuapp',
    authDomain: 'nhatkychitieuapp.firebaseapp.com',
    storageBucket: 'nhatkychitieuapp.firebasestorage.app',
    measurementId: 'G-5RR3VFPN3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsWK0643C2c6cAjbehY3br4tRYo2B8Dgg',
    appId: '1:791650293748:android:5890ebee70b55ab7224ba1',
    messagingSenderId: '791650293748',
    projectId: 'nhatkychitieuapp',
    storageBucket: 'nhatkychitieuapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQxTlg3micTejhYRIi1QHZymVuOiCWG64',
    appId: '1:791650293748:ios:f2b6913422dbeb64224ba1',
    messagingSenderId: '791650293748',
    projectId: 'nhatkychitieuapp',
    storageBucket: 'nhatkychitieuapp.firebasestorage.app',
    iosBundleId: 'com.example.nhatkychitieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQxTlg3micTejhYRIi1QHZymVuOiCWG64',
    appId: '1:791650293748:ios:f2b6913422dbeb64224ba1',
    messagingSenderId: '791650293748',
    projectId: 'nhatkychitieuapp',
    storageBucket: 'nhatkychitieuapp.firebasestorage.app',
    iosBundleId: 'com.example.nhatkychitieu',
  );
}
